[package]
name = "blob_retriever"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beacon-api-client = { git = "https://github.com/ralexstokes/beacon-api-client" } 
